config/routes.rb
Rails.application.routes.draw do
	mount Bootsy::Engine => '/bootsy', as: 'bootsy'

	resources :messages, only: [:new, :create]


	devise_for :users, :controllers => { registrations: 'registrations'}  
	root 'welcome#home'

	get "/about" => "welcome#about"
	get "/packages" => "welcome#packages"
	get "/contact" => "welcome#contact"

	get "/blog/editor" => "editors#index"
	get "/blog/editor/new" => "editors#new", :as => :editor_new
	post "/blog/editor/new" => "editors#create"
	get "/blog/editor/drafts" => "editors#draft_list"

	# get "/blog" => "blog#home"
	resources :posts, path: '/blog' do
		resources :comments
		member do
			get 'like'
		end
	end

	# match '/send_order', to: 'welcome#send_order', via: 'post'

end

app/models/editor.rb
class Editor < User
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
	before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :owned_post, only: [:edit, :update, :destroy]
  before_action :is_editor

  layout 'editor'

  def index

  end

  def new
    @post = current_user.posts.build
  end

  def create

    @post = current_user.posts.build(post_params)

    if params[:create_post]
      @post.is_drafted = false
      @post.submitted = true
      @post.published = false
      if @post.save
        flash[:success] = "Your post has been submitted!"
        redirect_to blog_editor_path
      else
        flash[:alert] = "Your post couldn't be submitted!  Please check the form."
        render "new" 
      end
    elsif params[:draft_post]
      @post.is_drafted = true
      @post.submitted = false
      @post.published = false
      if @post.save
        flash[:success] = "Your post has been saved!"
        redirect_to blog_editor_path
      else
        flash[:alert] = "Your post couldn't be saved!  Please check the form."
        render "new" 
      end
    end

    # redirect_to blog_editor_new_path

  end

  def draft_list
    @posts = Post.where(is_drafted: true).all.order('created_at DESC').page params[:page]    
  end



  private

  def post_params
    params.require(:post).permit(:title, :content, :bootsy_image_gallery_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

  def is_editor

  	if current_user.is_a? Editor

  	else
      flash[:alert] = "You are not an author, don't try to fool us -__-"
      redirect_to root_path
    end    
  end

end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/views/editors/_post.html.erb
<!-- <div class="posts-wrapper">
  <div class="post">
    <div class="post-head" style="background-image: <%= post.image.url(:medium) %>;">
      <h2><%= post.title %></h2>
    </div>
    <div class="post-caption">
    <p><%= post.content %></p>
    </div>
    
  </div>
</div> -->


<div class="">
  <%= image_tag post.image.url(:medium), class:'img-responsive thumbnail' %>
  <div class="wrapper">
    <div class="caption post-content">

      <h3><%= post.title %></h3>
      <p><%= post.content %></p>  

    </div>
  </div>
</div>

app/views/editors/create_post.html.erb
<!-- Page Content -->
<div id="page-content-wrapper">
	<a href="#menu-toggle" class="btn btn-primary" id="menu-toggle">Toggle Menu</a>  
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">
				<%= form_for @post do |f| %>

				<% if @post.errors.any? %>
				<div id="error_explanation">
					<h2>
						<%= pluralize(@post.errors.count, "error") %> prohibited
						this post from being saved:
					</h2>
					<ul>
						<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
				<% end %>

				<div class="form-group">
					<%= f.label :title %>
					<%= f.text_field :title, class: "form-control", placeholder:"Title" %>
				</div>

				<div class="form-group">
					<%= f.label :content %>
					<%= f.bootsy_area :content, class: "form-control", placeholder:"Content", rows: 16 %>
				</div>

				<%= f.submit %>
				<% end %>

			</div>
		</div>
	</div>
</div>
<!-- /#page-content-wrapper -->

app/views/editors/draft_list.html.erb
<!-- Page Content -->
<!-- <div id="page-content-wrapper">
-->	
<a href="#menu-toggle" class="btn btn-primary" id="menu-toggle">Toggle Menu</a>        

<div class="container-fluid">

	<% @posts.in_groups_of(2).each do |group| %>
	<div class="row">
		<% group.each do |post| %>
		<div class="col-lg-6">
			<%= render 'post', post: post %>
		</div>
		<% end %>
	</div>
	<% end %>

	<%= paginate @posts %>
</div>
<!-- </div> -->
<!-- /#page-content-wrapper -->


<%= link_to "Create Post", blog_editor_new_path, :class => "btn btn-primary create-post-btn"%>

app/views/editors/index.html.erb
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <a href="#menu-toggle" class="btn btn-primary" id="menu-toggle">Toggle Menu</a>        

            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Simple Sidebar</h1>
                        <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                        
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->


        <%= link_to "Create Post", blog_editor_new_path, :class => "btn btn-primary create-post-btn"%>

    

app/views/editors/new.html.erb
<div id="page-content-wrapper">
	<a href="#menu-toggle" class="btn btn-primary menu-toggle" id="menu-toggle">Toggle Menu</a>  
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12">

				<%= form_for @post, :url => editor_new_path do |f| %>

				<% if @post.errors.any? %>
				<div id="error_explanation">
					<h2>
						<%= pluralize(@post.errors.count, "error") %> prohibited
						this post from being saved:
					</h2>
					<ul>
						<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
				<% end %>

				<div class="form-group">
					<%= f.label :title %>
					<%= f.text_field :title, class: "form-control", placeholder:"Title" %>
				</div>

				<div class="form-group">
					<%= f.label :content %>
					<%= f.bootsy_area :content, class: "form-control", placeholder:"Content", rows: 16 %>
				</div>

				<%= submit_tag 'Submit Post', name: 'create_post' %>
				<%= submit_tag 'Draft Post', name: 'draft_post' %>
				<% end %>

			</div>
		</div>
	</div>
</div>
<!-- /#page-content-wrapper