config/routes.rb
Rails.application.routes.draw do
	mount Bootsy::Engine => '/bootsy', as: 'bootsy'

	resources :messages, only: [:new, :create]


	devise_for :users, :controllers => { registrations: 'registrations'}  
	root 'welcome#home'

	get "/about" => "welcome#about"
	get "/packages" => "welcome#packages"
	get "/contact" => "welcome#contact"

	get "/blog/editor" => "editors#index"
	get "/blog/editor/new" => "editors#new", :as => :editor_new
	post "/blog/editor/new" => "editors#create"
	get "/blog/editor/drafts" => "editors#draft_list"

	# get "/blog" => "blog#home"
	resources :posts, path: '/blog' do
		resources :comments
		member do
			get 'like'
		end
	end

	# match '/send_order', to: 'welcome#send_order', via: 'post'

end

app/views/layouts/_blog_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Photogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <%= link_to "New Post", new_post_path %>
        </li>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Register", new_user_registration_path %>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_editor_navbar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="text-center sidebar-brand">
            <a href="#">Golemtron</a>
        </li>
        
        <li class="text-center"><%= image_tag current_user.avatar.url(:thumb), class:'center-block img-responsive editor-circle' %>
        </li>

        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Published</a>
        </li>
        <li>
            <a href="#">Under Review</a>
        </li>
        <li>
            <%= link_to "Drafts", blog_editor_drafts_path %>
        </li>
        <li>
            <a href="#">Setting</a>
        </li>
        <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
        <li>
            <a href="#">Contact</a>
        </li>

    </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Golemtron - IT and Branding Solutions</title>
	<meta name="description" content="Golemtron provides creative solutions for your business problems. From software solutions to branding and marketing, we got it all covered." />
	<meta name="keywords" content="Golemtron, Social Media Marketing, SEO, Development, Automation, Programming, Software Solutions, E-Commerece Solutions, Android Development, IOS Development, Mobile Apps Development, Web Development, Desktop Applications, Scalable Software" />
	<meta name="author" content="golemtron.com" />

	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>
<body>
	<%= yield %>
</body>

</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golemtron - Blog</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <meta name="description" content="Golemtron provides creative solutions for your business problems. From software solutions to branding and marketing, we got it all covered." />
  <meta name="keywords" content="Golemtron, Social Media Marketing, SEO, Development, Automation, Programming, Software Solutions, E-Commerece Solutions, Android Development, IOS Development, Mobile Apps Development, Web Development, Desktop Applications, Scalable Software" /> -->
  <meta name="author" content="golemtron.com" />

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<%= render 'layouts/blog_navbar' %>


<div class="container">
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
  <%= yield %>
</div>




</body>
</html>

app/views/layouts/editor.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golemtron - Editor View</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <meta name="description" content="Golemtron provides creative solutions for your business problems. From software solutions to branding and marketing, we got it all covered." />
  <meta name="keywords" content="Golemtron, Social Media Marketing, SEO, Development, Automation, Programming, Software Solutions, E-Commerece Solutions, Android Development, IOS Development, Mobile Apps Development, Web Development, Desktop Applications, Scalable Software" /> -->
  <meta name="author" content="golemtron.com" />

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'editors', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

      </head>

      <body>

        <div id="wrapper">

          <%= render 'layouts/editor_navbar' %>

          <div id="page-content-wrapper">
            <div class="container-fluid">
              <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, class: "alert alert-info" %>
              <% end %>
            </div>
          </div>


          <%= yield %>

        </div>
        <!-- /#wrapper -->

        <!-- Menu Toggle Script -->
        <script>
          $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
          });
        </script>

      </body>

      </html>